/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RutAvdragRouteImport } from './routes/rut-avdrag'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as OffertRouteImport } from './routes/offert'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as AdminTimeTrackingRouteImport } from './routes/admin/time-tracking'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminChecklistsRouteImport } from './routes/admin/checklists'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin/leads.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings.index'

const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RutAvdragRoute = RutAvdragRouteImport.update({
  id: '/rut-avdrag',
  path: '/rut-avdrag',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const OffertRoute = OffertRouteImport.update({
  id: '/offert',
  path: '/offert',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StaffRoute,
} as any)
const AdminTimeTrackingRoute = AdminTimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChecklistsRoute = AdminChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
  '/om-oss': typeof OmOssRoute
  '/rut-avdrag': typeof RutAvdragRoute
  '/staff': typeof StaffRouteWithChildren
  '/tjanster': typeof TjansterRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/time-tracking': typeof AdminTimeTrackingRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
  '/om-oss': typeof OmOssRoute
  '/rut-avdrag': typeof RutAvdragRoute
  '/staff': typeof StaffRouteWithChildren
  '/tjanster': typeof TjansterRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/time-tracking': typeof AdminTimeTrackingRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
  '/om-oss': typeof OmOssRoute
  '/rut-avdrag': typeof RutAvdragRoute
  '/staff': typeof StaffRouteWithChildren
  '/tjanster': typeof TjansterRoute
  '/admin/checklists': typeof AdminChecklistsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/time-tracking': typeof AdminTimeTrackingRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kontakt'
    | '/offert'
    | '/om-oss'
    | '/rut-avdrag'
    | '/staff'
    | '/tjanster'
    | '/admin/checklists'
    | '/admin/content'
    | '/admin/login'
    | '/admin/schedule'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/admin/time-tracking'
    | '/staff/login'
    | '/admin/'
    | '/admin/bookings/'
    | '/admin/customers/'
    | '/admin/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/offert'
    | '/om-oss'
    | '/rut-avdrag'
    | '/staff'
    | '/tjanster'
    | '/admin/checklists'
    | '/admin/content'
    | '/admin/login'
    | '/admin/schedule'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/admin/time-tracking'
    | '/staff/login'
    | '/admin'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kontakt'
    | '/offert'
    | '/om-oss'
    | '/rut-avdrag'
    | '/staff'
    | '/tjanster'
    | '/admin/checklists'
    | '/admin/content'
    | '/admin/login'
    | '/admin/schedule'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/testimonials'
    | '/admin/time-tracking'
    | '/staff/login'
    | '/admin/'
    | '/admin/bookings/'
    | '/admin/customers/'
    | '/admin/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  OffertRoute: typeof OffertRoute
  OmOssRoute: typeof OmOssRoute
  RutAvdragRoute: typeof RutAvdragRoute
  StaffRoute: typeof StaffRouteWithChildren
  TjansterRoute: typeof TjansterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rut-avdrag': {
      id: '/rut-avdrag'
      path: '/rut-avdrag'
      fullPath: '/rut-avdrag'
      preLoaderRoute: typeof RutAvdragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offert': {
      id: '/offert'
      path: '/offert'
      fullPath: '/offert'
      preLoaderRoute: typeof OffertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof StaffRoute
    }
    '/admin/time-tracking': {
      id: '/admin/time-tracking'
      path: '/time-tracking'
      fullPath: '/admin/time-tracking'
      preLoaderRoute: typeof AdminTimeTrackingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/checklists': {
      id: '/admin/checklists'
      path: '/checklists'
      fullPath: '/admin/checklists'
      preLoaderRoute: typeof AdminChecklistsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminChecklistsRoute: typeof AdminChecklistsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTimeTrackingRoute: typeof AdminTimeTrackingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminChecklistsRoute: AdminChecklistsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTimeTrackingRoute: AdminTimeTrackingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StaffRouteChildren {
  StaffLoginRoute: typeof StaffLoginRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffLoginRoute: StaffLoginRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KontaktRoute: KontaktRoute,
  OffertRoute: OffertRoute,
  OmOssRoute: OmOssRoute,
  RutAvdragRoute: RutAvdragRoute,
  StaffRoute: StaffRouteWithChildren,
  TjansterRoute: TjansterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
