/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as RutAvdragRouteImport } from './routes/rut-avdrag'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as OffertRouteImport } from './routes/offert'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin/leads.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings.index'

const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const RutAvdragRoute = RutAvdragRouteImport.update({
  id: '/rut-avdrag',
  path: '/rut-avdrag',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const OffertRoute = OffertRouteImport.update({
  id: '/offert',
  path: '/offert',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
  '/om-oss': typeof OmOssRoute
  '/rut-avdrag': typeof RutAvdragRoute
  '/tjanster': typeof TjansterRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
  '/om-oss': typeof OmOssRoute
  '/rut-avdrag': typeof RutAvdragRoute
  '/tjanster': typeof TjansterRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
  '/om-oss': typeof OmOssRoute
  '/rut-avdrag': typeof RutAvdragRoute
  '/tjanster': typeof TjansterRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kontakt'
    | '/offert'
    | '/om-oss'
    | '/rut-avdrag'
    | '/tjanster'
    | '/admin/'
    | '/admin/bookings/'
    | '/admin/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/offert'
    | '/om-oss'
    | '/rut-avdrag'
    | '/tjanster'
    | '/admin'
    | '/admin/bookings'
    | '/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kontakt'
    | '/offert'
    | '/om-oss'
    | '/rut-avdrag'
    | '/tjanster'
    | '/admin/'
    | '/admin/bookings/'
    | '/admin/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  OffertRoute: typeof OffertRoute
  OmOssRoute: typeof OmOssRoute
  RutAvdragRoute: typeof RutAvdragRoute
  TjansterRoute: typeof TjansterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rut-avdrag': {
      id: '/rut-avdrag'
      path: '/rut-avdrag'
      fullPath: '/rut-avdrag'
      preLoaderRoute: typeof RutAvdragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offert': {
      id: '/offert'
      path: '/offert'
      fullPath: '/offert'
      preLoaderRoute: typeof OffertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KontaktRoute: KontaktRoute,
  OffertRoute: OffertRoute,
  OmOssRoute: OmOssRoute,
  RutAvdragRoute: RutAvdragRoute,
  TjansterRoute: TjansterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
